    ---
title: "Revisitando uma visualização"
output: html_notebook
---

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(htmlwidgets)
library(plotly)
library(here)
theme_set(theme_bw())
```


```{r}
dados = read_csv(here("data/series_from_imdb.csv"), 
                    progress = FALSE,
                    col_types = cols(.default = col_double(), 
                                     series_name = col_character(), 
                                     episode = col_character(), 
                                     url = col_character(),
                                     season = col_character())) %>% 
                                    filter(series_name %in% c("Dexter", "How I Met Your Mother")) 

dexter <- dados %>% filter(series_name == "Dexter") 
himym <- dados %>% filter(series_name == "How I Met Your Mother") 

```

```{r}

f <- list(
  family = "Courier New, monospace",
  size = 18,
  color = "#7f7f7f"
)
y <- list(
  title = "Total de votos",
  titlefont = f
)
x <- list(
  title = "Média IMDB",
  titlefont = f
)

p <- plot_ly(dados, type="scatter", mode="markers+text+legends",
             y = ~user_votes, 
             x = ~user_rating, 
             size= ~user_votes, 
             color= ~series_name,
             hovertext= ~paste("Episódio:", episode, '<br>S', season, 'E', season_ep)) %>%
    layout(xaxis = x, yaxis = y)
p
    
```